services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: cognitive_hub_api_${ENV_NAME}
    ports:
      - "${API_PORT}:8000"
    environment:
      - ENV=${ENV_NAME}
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: cognitive_hub_client_${ENV_NAME}
    ports:
      - "${CLIENT_PORT}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${PUBLIC_API_URL}
    depends_on:
      - api
    restart: unless-stopped